### ISSUE TITLE
Error in DiffusionTransformer residual connection

### ISSUE THREAD

**Issue by Buddha7771** [lucidrains/alphafold3-pytorch#113]
https://github.com/lucidrains/alphafold3-pytorch/blob/d5616fafb5542c77260c3c2f9ec61bf97dbd50a8/alphafold3_pytorch/alphafold3.py#L1679-L1680

I think I found an error in your code: it should be `noised_repr = ff_out + attn_out + residual`.
Also, I really agree with your comment that there is an error in the AF3 pseudocode (Algorithm 23).

**Comment by lucidrains** [comment]
@Buddha7771 oops, yes, thank you!

and yea, i think serial is the way to go
