### ISSUE TITLE
Usage of atom_ref_pos_to_atompair_inputs

### ISSUE THREAD

**Issue by twidatalla** [lucidrains/alphafold3-pytorch#122]
Hi @lucidrains 

Thank you so much for this work. I am trying to match up the Pseudocode of "Algorithm 20" from the supplemental to your implementation, and can't find where lines 2-6 of "Algorithm 5" (which is included in your implementation of Algorithm 20) are within the forward method of `DiffusionModule(Module):` which is meant to implement Algorithm 20 to my understanding of the code. 

I see you have the function `def atom_ref_pos_to_atompair_inputs` declared in `alphafold3.py` which performs lines 2-6, but as far as I can see you don't use it?

Best,
Talal

**Comment by lucidrains** [comment]
hey Talal! thanks for reviewing the code and indeed I never integrated this function!

will get it tested this weekend and then it belongs somewhere here https://github.com/lucidrains/alphafold3-pytorch/blob/main/alphafold3_pytorch/inputs.py#L310

**Comment by lucidrains** [comment]
@twidatalla should be good now!

**Comment by twidatalla** [comment]
Thanks for the quick fix!
