### ISSUE TITLE
`repeat_batch_interleave` seems broken when `batch_size > 1`

### ISSUE THREAD

**Issue by amorehead** [lucidrains/alphafold3-pytorch#158]
For the function https://github.com/lucidrains/alphafold3-pytorch/blob/29948041dbfbb963fe863ca1e873de8786f3feeb/alphafold3_pytorch/alphafold3.py#L327 I noticed it is returning all mask values for the first element in my batch of size `2`.

Here are the inputs I passed to the function to get this erroneous result:
```python
# asym_id
# tensor([[ 0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
#         [ 1,  0,  0,  1,  1,  0,  0,  1,  0,  1,  0,  1,  0,  1,  1]],
#       device='cuda:0')

# molecule_atom_lens
# tensor([[ 1,  7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
#        [ 1,  3,  1,  2,  3,  2,  1,  2,  3,  2,  2,  3,  2,  3, 30]],
#       device='cuda:0')

# called as:
atom_asym_id = batch_repeat_interleave(asym_id, molecule_atom_lens, mask_value=-1)

# output:
# atom_asym_id
# tensor([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
#          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
#          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
#          -1, -1, -1, -1, -1, -1],
#         [ 1,  0,  0,  0,  0,  1,  1,  1,  1,  1,  0,  0,  0,  1,  1,  0,  0,  0,
#           1,  1,  0,  0,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
#           1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
#           1,  1,  1,  1,  1,  1]], device='cuda:0')
```

**Comment by lucidrains** [comment]
@amorehead ohh, so i think there is some misunderstanding with the kwarg name, `mask_value` actually refers to the output padding. so when you passed in negative lengths, it did not calculate the correct total length of that batch element

i added a clamp to protect against that and renamed the kwarg

**Comment by lucidrains** [comment]
@amorehead i fixed the collation to use 0's for `molecule_atom_lens` too

ugh, i didn't design that part of the project too well 🤣
