### ISSUE TITLE
Double `LayerNorm` in `PairwiseBlock`

### ISSUE THREAD

**Issue by alexanderbonnet** [lucidrains/alphafold3-pytorch#189]
Fun stuff you guys are doing here!

There seem to be two `LayerNorm` layers applied to the inputs of the `TriangleMultiplication` layers in the `PairwiseBlock`, one with a `PreLayerNorm` and another inside the layer itself.

https://github.com/lucidrains/alphafold3-pytorch/blob/f9393458671f7b4bc1d96ea43c571fcf149b8113/alphafold3_pytorch/alphafold3.py#L887-L888

https://github.com/lucidrains/alphafold3-pytorch/blob/f9393458671f7b4bc1d96ea43c571fcf149b8113/alphafold3_pytorch/alphafold3.py#L699

**Comment by lucidrains** [comment]
@alexanderbonnet thanks Alexander ☺️ should be fixed

**Comment by alexanderbonnet** [comment]
Sweet!
