### ISSUE TITLE
Modified polymer residues need to have a catch-all atom type

### ISSUE THREAD

**Issue by amorehead** [lucidrains/alphafold3-pytorch#209]
* Per CyaNine's error in parsing `2mtz-assembly1` into a `Biomolecule` object, it seems modified polymer residues need to have a catch-all atom type in their `residue_constants.atom_types` list.

**Comment by Kaihui-Cheng** [comment]
Yeah, thanks Alex!  The  `res_chem_comp_details.type` named `D-gamma-peptide, C-delta linking` ,  and when processing the atom named `OXT` , get 
```
pos[residue_constants.atom_order[atom_name]] = atom.coord
KeyError: 'ATM' 
```
 Maybe need to another approach for retrieving `residue_constants`, or something else.

**Comment by amorehead** [comment]
Thanks again @Kaihui-Cheng for pointing out this issue. Using [this PR](https://github.com/lucidrains/alphafold3-pytorch/pull/212), I can now successfully parse and train on `2mtz-assembly1`. Let me know if you have any other questions or find any other bugs.

**Comment by Kaihui-Cheng** [comment]
That’s great, thanks!
