### ISSUE TITLE
A question about token_bond

### ISSUE THREAD

**Issue by ZhonghuiGu** [lucidrains/alphafold3-pytorch#232]
Hi, thank you guys for implementing such a complicate work!

I am not sure if the variable `token_bond` is set appropriately.

```python
import torch
from alphafold3_pytorch import (
    Alphafold3,
    Alphafold3Input,
    alphafold3_inputs_to_batched_atom_input
)
eval_alphafold3_input = Alphafold3Input(
    proteins = ['AG', 'CDG', 'AG', 'CDG']
)
print(batched_atom_input.token_bonds[0][4][5])  ### true
```

The result shows that a bond is defined between  the 'G' from the second chain 'CDG' and the 'A' from the third chain 'AG'.
Which may be caused by the `asym_ids` does not take the symmetry of chain into consideration. https://github.com/lucidrains/alphafold3-pytorch/blob/57d466154ecd3666c035f509fa67971f6323655c/alphafold3_pytorch/inputs.py#L950

I guess that change it into `is_first_mol_in_chains = (asym_ids[1:] - asym_ids[:-1]) !=0 ` may fix it.

**Comment by lucidrains** [comment]
@ZhonghuiGu 🤦 yes you are right

thank you Zhonghui!
