### ISSUE TITLE
 ModuleNotFoundError: No module named 'alphafold3_pytorch.models'

### ISSUE THREAD

**Issue by Daisyli95** [lucidrains/alphafold3-pytorch#241]
Dear Sir/Madam, 

When trying to cluster the filtered data for the validation set, we run:

python scripts/cluster_pdb_val_mmcifs.py --mmcif_dir ./data/pdb_data/val_mmcifs/ --reference_clustering_dir ./data/pdb_data/data_caches/train_clusterings/ --output_dir ./data/pdb_data/data_caches/val_clusterings/ --clustering_filtered_pdb_dataset

but the bug occurs:
Loading CCD component SMILES strings from data/ccd_data/components_smiles.json.
Traceback (most recent call last):
  File "/raid/home/yaoxj/lijing/code/alphafold3-pytorch/scripts/cluster_pdb_val_mmcifs.py", line 51, in <module>
    from alphafold3_pytorch.models.components.inputs import CCD_COMPONENTS_SMILES
ModuleNotFoundError: No module named 'alphafold3_pytorch.models'

After checking the uploaded files, there are indeed no modules or directories called "models", which is often part of the components for a repository. Would you please help me with the issue? Thanks in advance.

**Comment by lucidrains** [comment]
@Daisyli95 hey, want to try again?

**Comment by Daisyli95** [comment]
Yeah, I tried again, still the error occurs....Seems strange to me that I could successfully cluster the training set, but not the validation set.
<img width="1388" alt="捕获1" src="https://github.com/user-attachments/assets/7ad30a5a-3fca-416b-b327-99ad6dafabe2">

**Comment by lucidrains** [comment]
@Daisyli95 i don't think you actually updated the code

**Comment by Daisyli95** [comment]
Many thanks. After updating the files, it works.
