### ISSUE TITLE
Request to add protein language embeddings as input

### ISSUE THREAD

**Issue by rakeshr10** [lucidrains/alphafold3-pytorch#246]
Hi @lucidrains and @amorehead,

  Is it possible to add protein language embeddings as an input and train the model, that way the structures can be predicted without MSA and templates just like in ESMFold or OpenFold-SoloSeq.

Regards
Rakesh

**Comment by lucidrains** [comment]
@rakeshr10 sure! did you have a specific model in mind?

**Comment by rakeshr10** [comment]
Hi @lucidrains ,

   I interested in ESM (https://github.com/facebookresearch/esm) and ProtT5 (https://github.com/agemagician/ProtTrans) and its variant ProstT5 (https://github.com/mheinzinger/ProstT5).
  
Regards
Rakesh

**Comment by lucidrains** [comment]
ProstT5 looks cool, let me think about it

**Comment by rakeshr10** [comment]
ProstT5 is a bidirectional language model it can convert sequence to 3d structure tokens and vice versa. 

The thing I think you would need to consider is the dimensions of the embeddings as input, I think ESM mean representation is 1024 and ProtT5 I guess is 1028. If I not wrong ESM is based on BERT and ProtT5 on T5. 

Just a pointer you could also take a look at how the ESMFold and OpenFold guys used embeddings as input to the structure module or the folding trunk.

Thanks for the great work you guys are doing.

**Comment by amorehead** [comment]
You read my mind @rakeshr10! Great idea

**Comment by amorehead** [comment]
@rakeshr10, I've implemented these ideas in [this PR](https://github.com/lucidrains/alphafold3-pytorch/pull/252)

**Comment by rakeshr10** [comment]
Great @amorehead ! Do you plan to release a model trained only on embeddings once the code is ready to train?

Also, is there a documentation on how to use the current code for training purposes and for inference for testing. Would be great if you could point me to it.

**Comment by amorehead** [comment]
@rakeshr10 You can check out my fork of this repo

**Comment by lucidrains** [comment]
@rakeshr10 this feature is now available, and one can even specify multiple plms
