### ISSUE TITLE
Problem with atom_pos  processing during training

### ISSUE THREAD

**Issue by Kaihui-Cheng** [lucidrains/alphafold3-pytorch#260]
Hi, Alex and Lucidrains. When I try to train AF3, I'm encountering an issue with the atom_pos processing before AtomAug. I can retrieve the shape of atom_pos, but it doesn't contain any elements. This occurs with the case: 207d-assembly1.cif. Could there be something wrong with the dataloader especially for interface of the ligands?
```
ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [113,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
```
<img width="800" alt="1726386918737" src="https://github.com/user-attachments/assets/f8c05fbb-66cc-44f6-93b3-5155fa0d1deb">

<img width="329" alt="1726382819299" src="https://github.com/user-attachments/assets/b7971e72-c9dc-4554-9755-eb6a77d8afb7">

**Comment by Kaihui-Cheng** [comment]
This is the `chain_seqs` and `chain_chem_types` from https://github.com/lucidrains/alphafold3-pytorch/blob/618c307635a09ffedc817b792513eb349fe4c5a2/alphafold3_pytorch/inputs.py#L2960

**Comment by lucidrains** [comment]
@Kaihui-Cheng hey Kaihui, could you give us a small script reproducing the error, attaching also the cif file producing the error?

**Comment by lucidrains** [comment]
@Kaihui-Cheng also, have you tried following the instructions to get a better stacktrace? `CUDA_LAUNCH_BLOCKING=1` etc

**Comment by Kaihui-Cheng** [comment]
@lucidrains Hi Lucidrains, I tried setting CUDA_LAUNCH_BLOCKING=1 to trace the error, and it seems the issue occurs during the `torch.gather` operation in the line `molecule_pos = distogram_pos.gather`, which leads to the error when forwarding with `207d`. 

You might be able to reproduce it using the attached `.csv` and `.cif` files, though it could take some time for the error to occur during training. 

Thanks for looking into this!

<img width="488" alt="1726416273874" src="https://github.com/user-attachments/assets/03da87c3-96c3-497e-baf5-a4f84bf0d00b">
https://github.com/lucidrains/alphafold3-pytorch/blob/618c307635a09ffedc817b792513eb349fe4c5a2/alphafold3_pytorch/alphafold3.py#L6793

[debug_mmcif_bk.zip](https://github.com/user-attachments/files/17006418/debug_mmcif_bk.zip)

**Comment by lucidrains** [comment]
@Kaihui-Cheng nice! i'll check it out tomorrow
