### ISSUE TITLE
Initial guess

### ISSUE THREAD

**Issue by johnny-rodriguez** [lucidrains/alphafold3-pytorch#263]
Feeding alphafold 2 an initial guess (PDB file of the binder:target complex structure) has been instrumental for protein binder design. 
See https://github.com/nrbennet/dl_binder_design for reference.

Is this something that can be incorporated?
Thanks in advance!

**Comment by lucidrains** [comment]
Alex is still trying to sail to the right point in high dimensional parameter space. but yes, once that point is captured, can add applications of that sort, binder design or whatever
