### ISSUE TITLE
G-quadruplex (G4) DNA

### ISSUE THREAD

**Issue by ZhuLvs** [lucidrains/alphafold3-pytorch#316]
Dear Developers,

I hope this message finds you well!
I would like to ask whether Alphafold3 supports the prediction of binding conformations between G-quadruplex (G4) DNA and proteins?

**Comment by lucidrains** [comment]
@ZhuLvs if it has learned tertiary structures of protein, why wouldn't it learn the secondary structure of nucleic acids?

**Comment by lucidrains** [comment]
@ZhuLvs yes, one of the hallmark of af3 is ability to learn on proteins and/or nucleic acids

**Comment by ZhuLvs** [comment]
Thank you very much for your response. My research topic focuses on the binding of proteins to G-quadruplexes, a special DNA structure. However, after multiple attempts using the AlphaFold server to predict the conformations of different proteins and G-quadruplex DNA, the confidence levels seem to be low, even for structures that have been experimentally validated. May I ask if AlphaFold3 has learned about this special DNA structure, the G-quadruplex? Thank you for your help!

<img width="509" alt="微信图片_20241119235720" src="https://github.com/user-attachments/assets/d6a4368f-032a-4ef3-b965-a3010a50891e">

**Comment by lucidrains** [comment]
@ZhuLvs it supports these types of predictions

whether they are any good is another matter
