### ISSUE TITLE
set expansion_factor=2 to be the same as the AF3.

### ISSUE THREAD

**Issue by luwei0917** [lucidrains/alphafold3-pytorch#39]
https://github.com/lucidrains/alphafold3-pytorch/blob/27991debe78f623572f6a0550ab9c4a6728675d1/alphafold3_pytorch/alphafold3.py#L1511

because at page 23 of the SI, under the 'def ConditionedTransitionBlock(a, s, n = 2)',
line 2, it says b should be dimension of R^(n*c) and n = 2.

**Comment by luwei0917** [comment]
https://github.com/lucidrains/alphafold3-pytorch/blob/27991debe78f623572f6a0550ab9c4a6728675d1/alphafold3_pytorch/alphafold3.py#L1962

P_std is 1.5 I think, due the first line in page 24.(before equation 7) of AF3 SI.

**Comment by lucidrains** [comment]
@luwei0917 thank you Wei!

**Comment by amorehead** [comment]
@luwei0917, typo in `apper` around these lines?
