### ISSUE TITLE
TypeError: Alphafold3.forward() got an unexpected keyword argument 'molecule_ids'

### ISSUE THREAD

**Issue by vinesmsuic** [lucidrains/alphafold3-pytorch#45]
Seems the latest codebase does not have `molecule_ids` in the `forward` function?
https://github.com/lucidrains/alphafold3-pytorch/blob/main/alphafold3_pytorch/alphafold3.py#L3213

The new codebase doesnt match with the example usage in the README.md.

**Comment by lucidrains** [comment]
it is here? https://github.com/lucidrains/alphafold3-pytorch/blob/main/alphafold3_pytorch/alphafold3.py#L3220

**Comment by vinesmsuic** [comment]
seems I might have accidentally modified the source file. Thanks for the prompt reply!
