### ISSUE TITLE
Position/token masking feature

### ISSUE THREAD

**Issue by thomashopf** [lucidrains/alphafold3-pytorch#49]
First of all, thank you for this wonderful piece of work!

Is there currently a way to specify a token/position mask in case different samples in the same batch have differing lengths, or are there any plans to add this to the implementation?

**Comment by thomashopf** [comment]
Just discovered this is inferred by `mask = molecule_atom_lens > 0`, apologies for false alarm

**Comment by lucidrains** [comment]
@thomashopf no problem! feel free to join the discord and voice any other issues you see (will be faster to get to a resolution when subjected to crowd wisdom)
