### ISSUE TITLE
The PairformerStack in TemplateEmbedder

### ISSUE THREAD

**Issue by fuxuliu** [lucidrains/alphafold3-pytorch#85]
Hi, I found a doubt. I hope I'm wrong.
About Algorithm 16 Template embedder
Line 9 should be pairformerstack, but I found out in your code TemplateEmbedder that you're using PairwiseBlock, which is just a module in pairformerstack, It also lacks AttentionPairBias and Transition layer, which are already implemented in the pairformerstack.

**Comment by fuxuliu** [comment]
But here's the weird thing
About Algorithm 16 Template embedder
The input of Line 9 pairformerstack is only pair repr. If pairformerstack is used, AttentionPairBias in pairformerstack also requires single repr as input. 
What do you think?

**Comment by lucidrains** [comment]
@fuxuliu yes that's right, i just assumed it was PairformerStack without the single representation blocks, which would be equivalent to what i have now; multiple PairformerBlocks

**Comment by lucidrains** [comment]
i don't think there is an issue, in other words

**Comment by fuxuliu** [comment]
okay, I get it.
