### ISSUE TITLE
Incorrect token molecule IDs?

### ISSUE THREAD

**Issue by amorehead** [lucidrains/alphafold3-pytorch#86]
The token molecule ID encoding https://github.com/lucidrains/alphafold3-pytorch/blob/85bb181ba7bf754f7aa6292da46b4e80f623d1fc/alphafold3_pytorch/inputs.py#L585

doesn't seem to match the AF3 paper. Instead, in the paper, DM mentions they used the following molecule ID encoding: 
```
# `proteins (20) | unknown protein (1) | rna (4) | unknown RNA (1) | dna (4) | unknown DNA (1) | gap (1)`,
# where ligands are mapped to the unknown protein category (i.e., molecule ID 20)
```
In other words, there should be 32 token types (proteins 0-19, unknown protein or any kind of ligand residue 20, RNA 21-25, DNA 26-30, gap 31).

**Comment by lucidrains** [comment]
@amorehead oh yup, got it lined up a bit better

**Comment by amorehead** [comment]
Thanks!
