### ISSUE TITLE
Wrong shape of `missing_atom_indices` after calling `pad_sequence`

### ISSUE THREAD

**Issue by amorehead** [lucidrains/alphafold3-pytorch#87]
When running https://github.com/lucidrains/alphafold3-pytorch/blob/34f8d44a72c7b023e4aa90b67101f2bd23472679/alphafold3_pytorch/inputs.py#L317
I noticed that `missing_atom_indices` should be of the same length as the number of `i.molecules`. However, here, it seems to me that my `missing_atom_indices`, which looks like the following at its tail end (and I can confirm `missing_atom_indices` matches the length of the number of `i.molecules`, i.e., `543`), is being padded incorrectly. For reference, the number of tokens (not molecules) in this complex I am testing with is `547`, so I would expect `missing_atom_indices` to be padded to length `547` while inserting these dummy `-1` values in the correct positions for missing atoms (essentially mapping from the number of molecules to the number of tokens).

On second thought, should these `missing_atom_indices` be padded in the first place? That doesn't seem right to me.

`missing_atom_indices`, which is a `list` of tensors of length `543`:
```python
532 =
tensor([], dtype=torch.int64)
533 =
tensor([], dtype=torch.int64)
534 =
tensor([], dtype=torch.int64)
535 =
tensor([], dtype=torch.int64)
536 =
tensor([], dtype=torch.int64)
537 =
tensor([], dtype=torch.int64)
538 =
tensor([], dtype=torch.int64)
539 =
tensor([], dtype=torch.int64)
540 =
tensor([], dtype=torch.int64)
541 =
tensor([5, 6, 7, 8])
542 =
tensor([5, 6, 7])
len() =
543
```

`missing_atom_indices` after calling `pad_sequence()`, which yields a tensor of shape `[543, 6]`:
```python
tensor([[-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1],
        ...,
        [-1, -1, -1, -1, -1, -1],
        [ 5,  6,  7,  8, -1, -1],
        [ 5,  6,  7, -1, -1, -1]])
```

**Comment by lucidrains** [comment]
@amorehead oh, this is mainly for handling if the distogram and token centre atom falls under a missing atom

could you try `0.1.133` and see if an appropriate error message pops up?

**Comment by amorehead** [comment]
The assert passes on my end with `0.1.133`. Both of these variables have the same length, yet the padding bit seems incorrect to me still. I think we need to keep track of another version of `missing_atom_indices` called `missing_token_indices` which is literally a copy of `missing_atom_indices` except that for ligand molecules it repeats the ligand molecule's missing atom indices for all (unfolded) atoms in the ligand.

**Comment by amorehead** [comment]
No worries. I can handle this in a PR for mmCIF files arriving here shortly.

**Comment by lucidrains** [comment]
@amorehead it has to do with ligands being one atom per token

i'll take care of it tomorrow 👍

**Comment by lucidrains** [comment]
actually, just took care of it now [here](https://github.com/lucidrains/alphafold3-pytorch/commit/2da0c5aeca0fd8d8481d91bf6bce1cbe068027ee)

**Comment by amorehead** [comment]
Nice!
